--Insert into foods table
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'BELL PEPPER', 'Bell peppers, also known as sweet peppers, are the fruit of a group of plants, the species Capsicum annuum. Plants of this species produce fruit in different colors, including red, yellow, orange, green, chocolate/brown, vanilla/white, and purple. Bell peppers are sometimes classified as less spicy but in the same category as sweet peppers', 12000);
INSERT INTO foods (category_id, name, description, price) VALUES (2, 'STRAWBERRY', 'The garden strawberry is a widely grown hybrid of the genus Fragaria. It is grown worldwide for its fruit. The fruit is preferred for its characteristic flavor, bright red color, interesting texture, and sweetness', 80000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'GREEN BEAN', 'Young peas, or immature peas, are unripe, unshelled and harvested immature or immature pods of the cultivar Phaseolus vulgaris.', 30000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'PURPLE CABBAGE', 'Purple cabbage is a type of cabbage, also known as cabbage, after being processed. Its leaves are dark red/purple. However, the plant changes color according to the pH value of the soil, due to a pigment belonging to anthocyanins.', 20000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'TOMATO', 'Tomato, belonging to the Ca family, is a vegetable for food. The fruit is initially green, turning yellow to red when ripe. Tomatoes have a slightly sour taste and are a nutritious food, rich in vitamins C and A, especially rich in healthy lycopeme.', 20000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'BROCOLLI', 'Broccoli is a plant of the species Wild Cabbage, with large flowers at the top, often used as a vegetable. Broccoli is usually prepared by boiling or steaming, but can also be eaten raw as a raw vegetable in appetizer plates.', 15000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'CARROTS', 'Carrot is a root vegetable, usually orange-yellow, red, yellow, white or purple. The edible part of the carrot is the tuber, which is actually its taproot, which contains many precursors of vitamin A, which is good for the eyes', 10000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'ONION', 'Most plants of the genus Onion are collectively referred to as onions. In practice, however, the word onion is generally used to refer to a plant species with the dichotomous name Allium cepa', 10000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'GARLIC', 'Garlic is a plant belonging to the Onion family, that is, it is related to onions, onions, shallots, leeks, etc., and is also used by humans as spices, drugs, and vegetables like relatives. its', 10000);
INSERT INTO foods (category_id, name, description, price) VALUES (2, 'APPLE', 'Apple', 15000);
INSERT INTO foods (category_id, name, description, price) VALUES (1, 'CHILLI', 'Chili is a fruit of plants of the genus Capsicum of the Ca family. Chili is a spice as well as a popular vegetable in the world. Chili is native to the Americas; Today it is grown all over the world and is used as a spice, vegetable, and medicine', 12000);
INSERT INTO foods (category_id, name, description, price) VALUES (3, 'APPLE JUICE', 'Apple juice is a favorite drink of many people. This is not only a delicious and refreshing drink, but also brings a lot of health benefits', 13000);
INSERT INTO foods (category_id, name, description, price) VALUES (4, 'DRIED LYCHEE', 'Dried lychee is a tonic, often used to treat diseases such as obesity, high blood pressure, flatulence, indigestion and neuralgia. However, if not used correctly, drying cloth will also harm the body', 14000);
-- INSERT INTO foods (category_id, name, description, price) VALUES ();
-- INSERT INTO foods (category_id, name, description, price) VALUES ();
-- INSERT INTO foods (category_id, name, description, price) VALUES ();
-- INSERT INTO foods (category_id, name, description, price) VALUES ();
-- INSERT INTO foods (category_id, name, description, price) VALUES ();